added line to check .next folder

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -16,6 +16,9 @@ jobs:
         run: npm i
       - name: Build Code
         run: npm run build
+      - name: Verify Build Output
+        run: |
+          ls -la .next || echo ".next directory not found!"
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
